version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gamingdb

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
